[package]
name = "ocpp-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
chrono = { version = "0.4", features = ["serde"] }
miette = { version = "7.6.0", features = ["serde", "fancy"] }
thiserror = "2.0.12"
